:::::::::::::: Seguimiento de Errores DynamoDB ::::::::::::::
4/09/2017 3:29:16 p. m. ==> País: BO - Usuario: 333333
Error message: Error al enviar la solicitud.
StackTrace:    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Portal.Consultoras.Common.LogManager.RegistrarDynamoDB(LogError logError) en E:\GitHub Source\Brench-MC-HD725\PortalConsultoras2\app\Portal.Consultoras.Common\LogManager\LogManager.cs:línea 141
Adicional: {"Aplicacion":"PORTALCONSULTORAS","Pais":"BO","Usuario":"333333","Mensaje":"No se puede obtener acceso al objeto desechado.\r\nNombre del objeto: 'System.ServiceModel.Channels.ServiceChannel'.","StackTrace":"\r\nServer stack trace: \r\n   en System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()\r\n   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)\r\n   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)\r\n\r\nException rethrown at [0]: \r\n   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)\r\n   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)\r\n   en Portal.Consultoras.Web.ServiceUsuario.IUsuarioService.RecuperarContrasenia(Int32 paisId, String correo)\r\n   en Portal.Consultoras.Web.ServiceUsuario.UsuarioServiceClient.RecuperarContrasenia(Int32 paisId, String correo) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Service References\\ServiceUsuario\\Reference.cs:línea 8416\r\n   en Portal.Consultoras.Web.Controllers.LoginController.RecuperarContrasenia(Int32 paisId, String textoRecuperacion) en E:\\GitHub Source\\Brench-MC-HD725\\PortalConsultoras2\\app\\Portal.Consultoras.Web\\Controllers\\LoginController.cs:línea 1454","Extra":{"Origen":"ServidorWeb","Url":"http://localhost:20267/Login/RecuperarContrasenia","Browser":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36","TipoTrace":"LogManager","Server":"PE-LPALQ00106"}}

InnerException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS.
InnerException: El certificado remoto no es válido según el procedimiento de validación.
